name: Build Browserstack UI-Test Wallet

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:

  build-app-and-upload:

    runs-on: ubuntu-latest

    outputs:
      app-url: ${{ steps.upload-app.outputs.app-url }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build with Gradle
      uses: ./.github/actions/gradle_docker
      with:
        gradle-cmd: wallet:assembleAbnRelease -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
    - name: upload artefact to Browserstack
      run: curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }} -X Post "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" -F "file=@/wallet/build/outputs/apk/abn/release/wallet-abn-release.apk" >> appResponse.json
    - id: upload-app
      run: echo ::set-output name=app-url::'$(jq -r '.app_url'  appResponse.json)

  build-test-suit-and-upload:

    runs-on: ubuntu-latest

    outputs:
      test-url: ${{ steps.upload-app.outputs.test-url }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build with Gradle
        uses: ./.github/actions/gradle_docker
        with:
          gradle-cmd: wallet:assembleAbnDebugAndroidTest -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
      - name: upload artefact to Browserstack
        run: curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }} -X Post "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" -F "file=@/wallet/build/outputs/apk/androidTest/abn/debug/wallet-abn-debug-androidTest.apk" >> test-suite-Response.json
      - id: upload-app
        run: echo ::set-output name=test-url::'$(jq -r '.test_url'  test-suite-Response.json)


  run-tests:
    runs-on: ubuntu-latest
    needs: [build-app-and-upload, build-test-suit-and-upload]

    steps:
      - name: run normal tests
        run: curl -u ${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }} -X Post "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" -d '{"app":${{ needs.build-app-and-upload.app-url }}, "testSuite":${{ needs.build-test-suit-and-upload.test_url }}, "devices":["Samsung Galaxy S9 Plus-9.0"]  }' -H "Content-Type:application/json"


